-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
--
-- Format-on-save: gerenciado pelo conform.nvim (configurado em plugins/formatting.lua)
-- Linting: gerenciado pelo nvim-lint (configurado em plugins/markdown-tools.lua e python-tools.lua)
-- Ambos sao inicializados automaticamente pelo LazyVim -- nao e necessario duplicar aqui.
